#write a program to input eight number from a user and display all the unique number (once)


s = set()
s1 = input("enter_a_number:-")
s2 = input("enter_a_number:-")
s3 = input("enter_a_number:-")
s4 = input("enter_a_number:-")
s5 = input("enter_a_number:-")
s6 = input("enter_a_number:-")
s7 = input("enter_a_number:-")
s8 = input("enter_a_number:-")
s.add(s1)
s.add(s2)
s.add(s3)
s.add(s4)
s.add(s5)
s.add(s6)
s.add(s7)
s.add(s8)
print(s)